export const CarListdata = [
    {
      id: 1,
      name: "Toyota Prius",
      seat: 4,
      desc: "A reliable and fuel-efficient hybrid car, perfect for city rides.",
      amount: 18.5,
      image: "/public/compressed_87e77cc19e46ecb3bc0d7a1ba4b8b734.webp",
    },
    {
      id: 2,
      name: "Honda Civic",
      seat: 4,
      desc: "A comfortable sedan with a spacious interior and smooth ride.",
      amount: 20.0,
      image: "/public/lovepik-white-car-png-image_400249558_wh300.png",
    },
    {
      id: 3,
      name: "Tesla Model 3",
      seat: 4,
      desc: "A premium electric car with advanced features and zero emissions.",
      amount: 30.0,
      image: "/public/Lovepik_com-400237161-white-car.png",
    },
    {
      id: 4,
      name: "Chevrolet Suburban",
      seat: 7,
      desc: "A large SUV with ample space, ideal for group travels or families.",
      amount: 45.0,
      image: "/public/pin.png",
    },
    {
      id: 5,
      name: "Ford Escape",
      seat: 5,
      desc: "A versatile and compact SUV suitable for urban and off-road trips.",
      amount: 25.0,
      image: "/public/pngtree-3d-car-model-png-image_14325000.png",
    },
    {
      id: 6,
      name: "BMW 5 Series",
      seat: 4,
      desc: "A luxury sedan offering premium comfort and performance.",
      amount: 50.0,
      image: "/public/pngtree-a-white-car-png-image_12555586.png",
    },
    {
      id: 7,
      name: "Mercedes-Benz V-Class",
      seat: 6,
      desc: "A high-end van offering luxury and space for larger groups.",
      amount: 60.0,
      image: "/public/pngtree-car-png-image_14994324.png",
    },
    {
      id: 8,
      name: "Hyundai Elantra",
      seat: 4,
      desc: "A modern sedan with a sleek design and great fuel efficiency.",
      amount: 18.0,
      image: "/public/pngtree-white-volkswagen-sedan-simulation-illustration-image_1191533.jpg",
    },
    {
      id: 9,
      name: "Jeep Wrangler",
      seat: 4,
      desc: "A rugged SUV designed for adventurous off-road experiences.",
      amount: 35.0,
      image: "/public/prague-1845560_1920.jpg",
    },
    {
      id: 10,
      name: "Kia Carnival",
      seat: 7,
      desc: "A spacious MPV for comfortable long-distance group travels.",
      amount: 40.0,
      image: "/public/White-car-sedan-on-transparent-background-PNG.png",
    },
  ];
  